project:
  type: website
  output-dir: docs

website:
  title: "BenVerst.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: resources.qmd
        text: Resources
        

format:
  html:
    theme: superhero
    css: bootstrap.css
    toc: true

editor: visual

