project:
  type: website
  output-dir: docs

website:
  title: "BenVerst.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: superhero
    css: styles.css
    dark: darkly
    toc: true

editor: visual

